### ISSUE TITLE
Create soil data input model and associated GraphQL mutations

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-backend#623]
## Description
Create a new model `SoilData` (or some better name) with a 1-1 relationship with `Site`, and columns for each data input tracking this issue. See discussion on https://github.com/techmatters/terraso-backend/issues/622 for guidance on the schema for data inputs with depth intervals.

```[tasklist]
### Tasks
- [x] Document design decisions
- [x] Make a new django app soil_id
- [x] Create a new model soil_data_inputs
- [x] Create a FK relationship to site
- [x] Add columns for the top and bottom of the depth interval
- [x] Add columns for different data inputs
- [x] Add new slope submethods
- [ ] Add GraphQL mutations for soil data
```

**Comment by ltseng** [comment]
Slope user story - https://github.com/techmatters/terraso-product/issues/158

**Comment by ltseng** [comment]
@shrouxm @david-code Since Jodie is no longer with us, will one of you be finishing this?

**Comment by shrouxm** [comment]
@ltseng yes, i was pairing with jodie on this so i will take it over!

**Comment by ltseng** [comment]
New potential data input requirement for soil texture, to be discussed next Tuesday:
- I can type the percentage of clay from 0 to 1-00% as an integer value.
